### ISSUE TITLE
[Android] Radio buttons not showing correctly on android

### ISSUE THREAD

**Issue by nombrekeff** [devhubapp/devhub#114]
### System Info
Android: 8.0
Samsung s8: 9.0
App version: 0.45.2

### Description
As you can see in the following image, radio buttons are not showing correctly:

![image](https://user-images.githubusercontent.com/17043260/52712091-e9c1c900-2f93-11e9-831f-ca18dff5d09c.png)

### Additional
Great work by the way!

**Comment by brunolemos** [comment]
Can you make a PR? I was not able to reproduce on my emulators.
This is the code: https://github.com/devhubapp/devhub/blob/3d043b6557a72a1c0e5c5e8c73a56a192acc830e/packages/components/src/components/widgets/ThemePreference.tsx#L93-L104

It was made this way because on some android the text was too small. But increasing it broke on your device. So we need to find a solution that works on any android.

We probably need to set the fontFamily to unify it for all devices.

**Comment by nombrekeff** [comment]
> Can you make a PR? I was not able to reproduce on my emulators.

Hi, sure, I've I have some time tonight I will try, otherwise I must wait until the weekend... 

> It was made this way because on some androids the text was too small. But increasing it broke on your device. We need to find a solution that works on all androids, so we can't just change the fontSize.

What about setting the font in some dinamic unit like rems (_don't know if this is posible the way with the technology used_)? As its related to screen size it will adjust to whatever screen size... I will test this...

I will update you, as I test stuff.

**Comment by brunolemos** [comment]
We can try. Thanks!

**Comment by brunolemos** [comment]
Had an issue with android app not being updated (#128), but this fix is live now.

**Comment by nombrekeff** [comment]
Cool, I will check later!
