### ISSUE TITLE
Private repositories stopped working

### ISSUE THREAD

**Issue by vokiel** [devhubapp/devhub#140]
The message is shown at https://devhubapp.com/

> Something went wrong
> Resource not accessible by integration
> Try again

In the console, I see `403 (Forbidden)` errors (for all private repositories):

```
GET https://api.github.com/repos/OWNER/REPOSITORY/events?access_token=REMOVED&page=1&per_page=50 403 (Forbidden)
bugsnag.js:2188 
Failed to load GitHub activity HttpError: Resource not accessible by integration
    at https://devhubapp.com/static/js/3.f24eecde.chunk.js:1:384879
```

DevHub App integration is installed on GitHub for selected repositories, OAuth set as well.

It was working like a week ago.

**Comment by brunolemos** [comment]
@vokiel thanks for reporting, I've contacted GitHub Support and I hope this is just a temporary mistake on their part. Let's wait for their answer.

**Comment by brunolemos** [comment]
I've exchanged some emails with GitHub, and the [CEO replied on twitter](https://twitter.com/natfriedman/status/1129521324542504961?s=21) as well. 

They disabled private access for security reasons. They don't have an ETA for the fix.

If I'm not willing to wait, the workaround is to use Webhooks instead of the events endpoint. That would require some considerable extra work, since I'd have to save everything in a database and build my own api on top of it. May increase costs. I may do it but I'm still considering, I haven't analysed yet how many DevHub users rely on this feature.

**Comment by brunolemos** [comment]
Support for private repositories is back!

There are good news and bad news.

Unfortunately GitHub has added some limitations. It will return only these events:

- Stars
- Created issues/prs
- State changes on issues/prs
- Comments on issues/prs

Unfortunately these other events are not being included anymore, unless I request the **code access** permission )which I don't plan to): 
- Pushed commits
- Comments inside commits
- Pull request reviews (review comment, approval, change request)
- Branch creation/deletion
- Tag creation/deletion
- Releases
- Forks

I have suggested to GitHub that they split the code permission into a separate permission, but we don't know if that will ever happen.

Good news is that the events that is is returning are already pretty useful!
