### ISSUE TITLE
UX regression on Android following 0.94.0 update

### ISSUE THREAD

**Issue by msfjarvis** [devhubapp/devhub#175]
The changes introduced in this update have significantly crippled my usability of the application. The ability to swipe and change tabs is completely gone, replaced with a bookmark feature on every item that I never use and cannot find a way to get rid of. I cannot understate how horrible the vibration pattern is on the gesture action. It's like a palm-sized jackhammer and that's on a Google Pixel 2, one of the better vibration motors out there. I'd REALLY appreciate the ability to completely get rid of these gestures and restore swipe behaviour to pre-0.94.0 because as of now, the app has become completely unusable for me :(

I don't mean anything above in a snide and hateful way, I appreciate your quick follow-ups to my previously reported issues. It's just that I personally feel very upset that a critical part of my daily workflow is now rendered unusable and that made my tone a tad bit aggressive and ungrateful, for which I sincerely apologise.

**Comment by brunolemos** [comment]
> horrible vibration pattern

Oops, this was a mistake, I deployed the vibration with the wrong value 😅

> get rid of these gestures

Swipe gestures will play an important role in the near future since there will be lot's of more actions like archiving, snoozing, etc. I don't plan removing them unless you have an alternative to suggest.

> ability to swipe and change tabs is completely gone

This has been the case for more than 4 months probably, but some Android devices like yours were still triggering the "multi-column" layout by mistake due to some screen resolution difference.

Maybe we can come up with a middle ground solution to have both "swipe gestures" on card and "horizontal scroll" on columns. But in the mean time, you can use the sidebar to change columns, people use it with no problem.

Let me know if you have any suggestion on a good UX that supports both "swipe" on cards and "horizontal scroll" on columns.

**Comment by msfjarvis** [comment]
> I recommend that you use the new Landscape mode, which has the behavior you want:
> 
> ![devhub-android-landscape](https://user-images.githubusercontent.com/619186/64096405-f2af9780-cd37-11e9-923d-3cbf108c87e9.png)
> 

It works perfectly, but it is pretty counter-intuitive to require users to change orientation for the ability to navigate with ease.

> > ability to swipe and change tabs is completely gone
> 
> This has been the case for more than 4 months probably, but some Android devices like yours were still triggering the "multi-column" layout by mistake due to some screen resolution difference. On Landscape mode it works.

<details>
<summary>Screenshot</summary>
![](https://i.imgur.com/4vEMUoD.png)
</details>

That's how it has always looked on my device, is that not how it's supposed to be?

> > get rid of these gestures
> 
> Swipe gestures will play an important role in the near future since there will be lot's of more actions like archiving, snoozing, etc. I don't plan removing them unless you have an alternative to suggest.
> 
> For the Portrait mode, maybe we can come up with a middle ground solution to have both "swipe gestures" on card and "horizontal scroll" on columns. Let me know if you have any suggestion on a good UX for that.

Being able to swipe across the top search bar + toolbar combination to switch tabs would be a decent compromise for me.

**Comment by msfjarvis** [comment]
Landscape also presents this bug on Android where the input dialog text for search queries is white text on a white background

<details>
<summary>Screenshot</summary>
![](https://i.imgur.com/eLNuDAI.png)
</details>

**Comment by brunolemos** [comment]
> Being able to swipe across the top search bar + toolbar combination to switch tabs would be a decent compromise for me.

Cool, I can add that

> input with white text on a white background

Could not reproduce this, what’s your os version? I tried it on Pixel 2 emulator, Android 9.

**Comment by msfjarvis** [comment]
> > input with white text on a white background
> 
> Could not reproduce this, what’s your os version? I tried it on Pixel 2 emulator, Android 9.

This is on Android 10 Beta 6 with the default light mode enabled. I know it's an unreleased beta but final rollout is only days away so I figured I'd report early on.

**Comment by brunolemos** [comment]
Ops I mentioned it wrong, mine is Android 10 as well, I just don't know which beta. When I try to update Android Studio gives an error.

![image](https://user-images.githubusercontent.com/619186/64142603-082dcb80-cde3-11e9-8dd3-59bf5d4903ad.png)

![image](https://user-images.githubusercontent.com/619186/64142648-44f9c280-cde3-11e9-9544-a35a6351d88e.png)

I would appreciate a pull request, otherwise it will probably not be fixed.
