### ISSUE TITLE
Add DevHub into Franz plugins

### ISSUE THREAD

**Issue by luongvo** [devhubapp/devhub#36]
I just created a [Franz](https://meetfranz.com/) plugin for DevHub at https://github.com/luongvo/franz-recipe-devhubapp and waiting for plugin deployed https://github.com/meetfranz/plugins/issues/236

It should be nice if we could use Franz via web, android, ios, windows, mac and also a plugin in Franz app :)
![image](https://user-images.githubusercontent.com/16315358/50045595-0f337300-00c8-11e9-9204-817241cc7911.png)

**Comment by luongvo** [comment]
While waiting for the author deploys it to be a production plugin, we could use this via a dev plugin :bye_bye_pal:https://github.com/meetfranz/plugins/blob/master/docs/integration.md#installation

**Comment by brunolemos** [comment]
Thanks! Is there anything I should do on my side?

Maybe this should be at the `devhubapp` organization?

**Comment by luongvo** [comment]
@brunolemos you can create a new empty repo on https://github.com/devhubapp as `franz-recipe`, I will push the code for you and redirect my repo to this repo also 🚀

**Comment by abdullahceylan** [comment]
Today, I was going to start to create this plugin :)

Thanks @luongvo

**Comment by brunolemos** [comment]
Moved the code to https://github.com/devhubapp/devhub-franz-recipe.
Please update the link on https://github.com/meetfranz/plugins/issues/236!

I'll close this because they just need to merge the PR there, or people can use it as a [dev recipe](https://github.com/meetfranz/plugins/blob/master/docs/integration.md#installation).

Thanks!
