### ISSUE TITLE
iOS: pull to refresh

### ISSUE THREAD

**Issue by avelino** [devhubapp/devhub#37]
When dragging down refresh timeline (feed) of active column
example
![h3eiyubns6u8qr8xwck nq_thumb_2806](https://user-images.githubusercontent.com/31996/50051931-ccdb5780-0102-11e9-9a1c-108155ed665d.jpg)

**Comment by brunolemos** [comment]
Not sure about it, because it already updates automatically every minute and that's the minimum interval allowed by github, otherwise it will trigger their rate limit. 

I detected that some accounts are already triggering the message `You have triggered an abuse detection mechanism` from github, probably because they have too many columns.

One thing I'm considering is increasing this 1 minute interval, and then it would make sense to add a pull to refresh.

**Comment by peppy** [comment]
I would just like to add my two cents that i'd prefer decreasing the default update rate and adding pull to refresh. Usual scenario is that I make some changes and want to immediately pull to confirm the changes I made. Another use case is getting an email notification and wanting to see the content of that in the DevHub feed immediately.
