### ISSUE TITLE
Feature request: read-only mode

### ISSUE THREAD

**Issue by matks** [devhubapp/devhub#83]
Hi ! I just wanted to share this feedback: the project looks great and I wanted to give it a try however when I go to https://devhubapp.com/ it asks me for github sign-in including **read and write rights** to my public repositories data.

As a maintainer of an opensource project I cant allow that, even if I trust you 😉 . Can you tell me what usage the write rights are needed for ? My guess is to discard notifications.

That's why I add this feature request idea: allow devhub to run on read-only mode (this means disabling the features which need write rights) for paranoid people like me.

**Comment by brunolemos** [comment]
Hi! DevHub doesn't need any code access. Unfortunately GitHub includes code and write permission when we ask for `public_repo`, which is required for starring repositories and other things.

See #32 and this open letter for details: https://github.com/dear-github/dear-github/issues/113

Since we don't have this "star repository" feature yet, I think we can remove this.

I'll be able to check later today.

**Comment by brunolemos** [comment]
v0.41.1 has been released with the `public_repo` permission removed.

**Comment by matks** [comment]
Thank you 😄 starting using devhub right now !
