### ISSUE TITLE
JSC on Android

### ISSUE THREAD

**Issue by pcooney10** [devhubapp/devhub#88]
Hey @brunolemos, super cool project, thanks for sharing !

Looking through the android configuration, it seems you are using [JSC](https://github.com/react-native-community/jsc-android-buildscripts) or `jsc-android` to "fix crashes caused by an old version of JavaScript." (#19 & #50)

Would you mind elaborating on this a bit more? This is not something included out of the box with `react-native init ...`, and I'm curious to learn more. It is my understanding that RN bundles JavaScriptCore with Android, and uses the OS's version of JavaScriptCore on iOS (the same one used for Safari).

Was it maybe only necessary because you on the bleeding edge with React, or was there other reasoning behind the decision?

Thanks !

**Comment by brunolemos** [comment]
Hi!

The version of JavaScriptCore that is included on Android by default is very (very) old. Like, from 2014. Which means it doesn't contain most of the new JavaScript features that we got in the past few years.

> I'm not sure if this is an Android thing or react-native's. You can see this repo for more details: https://github.com/react-native-community/jsc-android-buildscripts

I could have transpiled the code to ES5 and it would probably work. But I didn't want to for performance reasons (and to avoid unnecessary bloat and parse, since ES5 output is much bigger than ESNext).

Good news is that react-native 0.58 has finally upgraded the JSC version, so the new JavaScriptCore will be available for everyone by default!
